### ISSUE TITLE
Some issues related to explosions

### ISSUE THREAD

**Issue by Techirion** [Samsuik/Sakura#11]
```
com.destroystokyo.paper.exception.ServerInternalException: Entity threw exception at world:-26959.565338143475,63.96419366596944,-36307.959645494484
	at net.minecraft.world.level.World.a(World.java:1583)
	at net.minecraft.server.level.WorldServer.lambda$tick$9(WorldServer.java:926)
	at net.minecraft.world.level.entity.EntityTickList.a(EntityTickList.java:48)
	at net.minecraft.server.level.WorldServer.a(WorldServer.java:897)
	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1723)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:452)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1524)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1224)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NullPointerException: Cannot invoke "me.samsuik.sakura.entity.EntityState.momentum()" because the return value of "net.minecraft.world.entity.Entity.entityState()" is null
	at me.samsuik.sakura.explosion.SakuraExplosion.c(SakuraExplosion.java:73)
	at net.minecraft.world.level.Level.explode(Level.java:1672)
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1943)
	at net.minecraft.world.level.Level.explode(Level.java:1631)
	at net.minecraft.world.entity.vehicle.MinecartTNT.explode(MinecartTNT.java:135)
	at net.minecraft.world.entity.vehicle.MinecartTNT.hurt(MinecartTNT.java:89)
	at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:411)
	at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:211)
	at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:202)
	at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:304)
	at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:240)
	at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:113)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1419)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:1576)
	at net.minecraft.server.level.ServerLevel.lambda$tick$9(ServerLevel.java:926)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:48)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:897)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1723)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:452)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224)
	... 2 more
```

Players messing with Minecarts...

Probably unrelated and I'm unable to replicate but in some cases they've managed to crash the server (creative server so no idea what they managed to spawn this time):

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 2024-03-08 20:42:02
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.longs.LongArrayList.getLong(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$MapIterator.nextEntry(Long2ObjectOpenHashMap.java:663)
	at it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap$ValueIterator.next(Long2ObjectOpenHashMap.java:1168)
	at java.base/java.util.Collection.removeIf(Collection.java:583)
	at me.samsuik.sakura.local.config.LocalConfigManager.expire(LocalConfigManager.java:129)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1740)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:452)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1524)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1224)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:1583)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
```

**Comment by Samsuik** [comment]
Both issues should be fixed with 4f7b6d9564001e588f793f7d9555a96b3469877a and 91803759a8652e3637fc1cffa5fd710fb90128e5.
