### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "me.samsuik.sakura.entity.EntityState.momentum()" because the return value of "net.minecraft.world.entity.item.PrimedTnt.entityState()" is null

### ISSUE THREAD

**Issue by Techirion** [Samsuik/Sakura#22]
With this applied on top of latest Sakura 1.21.1:

```
From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
From: 
Date: Fri, 6 Sep 2024 00:46:59 +0200
Subject: [PATCH] Remove lambda from ticking guard


diff --git a/src/main/java/net/minecraft/server/level/ServerLevel.java b/src/main/java/net/minecraft/server/level/ServerLevel.java
index 588913ccd1ebae4278c46f578650a504824c25df..66048bdfbdca3f7e3b82c932699094112b5c8be1 100644
--- a/src/main/java/net/minecraft/server/level/ServerLevel.java
+++ b/src/main/java/net/minecraft/server/level/ServerLevel.java
@@ -744,7 +744,17 @@ public class ServerLevel extends Level implements WorldGenLevel, ca.spottedleaf.
                             // Sakura end - merge cannon entities
 
                             gameprofilerfiller.push("tick");
-                            this.guardEntityTick(this::tickNonPassenger, entity);
+                            try {
+                                this.tickNonPassenger(entity); // Leaves - changed
+                            } catch (Throwable throwable) {
+                                if (throwable instanceof ThreadDeath) throw throwable; // Paper
+                                // Paper start - Prevent block entity and entity crashes
+                                final String msg = String.format("Entity threw exception at %s:%s,%s,%s", entity.level().getWorld().getName(), entity.getX(), entity.getY(), entity.getZ());
+                                MinecraftServer.LOGGER.error(msg, throwable);
+                                getCraftServer().getPluginManager().callEvent(new com.destroystokyo.paper.event.server.ServerExceptionEvent(new com.destroystokyo.paper.exception.ServerInternalException(msg, throwable))); // Paper - ServerExceptionEvent
+                                entity.discard(org.bukkit.event.entity.EntityRemoveEvent.Cause.DISCARD);
+                                // Paper end - Prevent block entity and entity crashes
+                            }
                             gameprofilerfiller.pop();
                         }
                     }

```

I'd start seeing a lot of those errors:

```
[11:37:08] [Server thread/ERROR]: Entity threw exception at world:-2914.5099999904633,46.0,-4445.509999990463
java.lang.NullPointerException: Cannot invoke "me.samsuik.sakura.entity.EntityState.momentum()" because the return value of "net.minecraft.world.entity.item.PrimedTnt.entityState()" is null
	at me.samsuik.sakura.explosion.special.TntExplosion.startExplosion(TntExplosion.java:61) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at me.samsuik.sakura.explosion.special.SpecialisedExplosion.explode(SpecialisedExplosion.java:67) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.level.Level.explode(Level.java:1736) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1803) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.level.Level.explode(Level.java:1691) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.entity.item.PrimedTnt.explode(PrimedTnt.java:245) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.entity.item.PrimedTnt.tick(PrimedTnt.java:195) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1268) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:748) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:718) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1814) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:37:08] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Entity threw exception at world:-2914.5099999904633,46.0,-4445.509999990463
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:754)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:718)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1814)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
[11:37:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:37:08] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "me.samsuik.sakura.entity.EntityState.momentum()" because the return value of "net.minecraft.world.entity.item.PrimedTnt.entityState()" is null
[11:37:08] [Server thread/WARN]: 	at me.samsuik.sakura.explosion.special.TntExplosion.startExplosion(TntExplosion.java:61)
[11:37:08] [Server thread/WARN]: 	at me.samsuik.sakura.explosion.special.SpecialisedExplosion.explode(SpecialisedExplosion.java:67)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1736)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1803)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1691)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.entity.item.PrimedTnt.explode(PrimedTnt.java:245)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.entity.item.PrimedTnt.tick(PrimedTnt.java:195)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1268)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:748)
[11:37:08] [Server thread/WARN]: 	... 8 more
[11:37:08] [Server thread/ERROR]: Entity threw exception at world:-2912.4900000095367,46.0,-4445.490000009537
java.lang.NullPointerException: Cannot invoke "me.samsuik.sakura.entity.EntityState.momentum()" because the return value of "net.minecraft.world.entity.item.PrimedTnt.entityState()" is null
	at me.samsuik.sakura.explosion.special.TntExplosion.startExplosion(TntExplosion.java:61) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at me.samsuik.sakura.explosion.special.SpecialisedExplosion.explode(SpecialisedExplosion.java:67) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.level.Level.explode(Level.java:1736) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1803) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.level.Level.explode(Level.java:1691) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.entity.item.PrimedTnt.explode(PrimedTnt.java:245) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.entity.item.PrimedTnt.tick(PrimedTnt.java:195) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1268) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:748) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:718) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1814) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331) ~[sakura-1.21.1.jar:1.21.1-DEV-b7e6fbe]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:37:08] [Server thread/WARN]: com.destroystokyo.paper.exception.ServerInternalException: Entity threw exception at world:-2912.4900000095367,46.0,-4445.490000009537
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:754)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:718)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1814)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1606)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1311)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:331)
[11:37:08] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:37:08] [Server thread/WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "me.samsuik.sakura.entity.EntityState.momentum()" because the return value of "net.minecraft.world.entity.item.PrimedTnt.entityState()" is null
[11:37:08] [Server thread/WARN]: 	at me.samsuik.sakura.explosion.special.TntExplosion.startExplosion(TntExplosion.java:61)
[11:37:08] [Server thread/WARN]: 	at me.samsuik.sakura.explosion.special.SpecialisedExplosion.explode(SpecialisedExplosion.java:67)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1736)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1803)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.level.Level.explode(Level.java:1691)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.entity.item.PrimedTnt.explode(PrimedTnt.java:245)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.world.entity.item.PrimedTnt.tick(PrimedTnt.java:195)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1268)
[11:37:08] [Server thread/WARN]: 	at net.minecraft.server.level.ServerLevel.lambda$tick$5(ServerLevel.java:748)
[11:37:08] [Server thread/WARN]: 	... 8 more
...
```

Missing null check?

**Comment by Samsuik** [comment]
> https://github.com/Samsuik/Sakura/blob/47b54e696ff75732a3c884ec5070e88c58b65e9d/patches/server/0015-Store-Entity-Data-State.patch#L86-L90

`entity.storeEntityState` has to be called before `this.tickNonPassenger`
